[package]
name = "native-term-shim"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "nativeterm-shim"
path = "src/main.rs"

[dependencies]
native-term-i18n = { path = "../native-term-i18n" }
i18n-embed = { version = "0.16", features = ["fluent-system"] }
i18n-embed-fl = "0.10"
native-term-config = { path = "../native-term-config" }
native-term-session = { path = "../native-term-session" }
native-term-win = { path = "../native-term-win" }
zmodem2 = "0.7"

[target.'cfg(windows)'.dependencies]
windows = { version = "0.62.2", features = [
    "Win32_Foundation",
    "Win32_NetworkManagement_IpHelper",
    "Win32_Networking_WinSock",
    "Win32_Security",
    "Win32_Storage_FileSystem",
    "Win32_System_Console",
    "Win32_System_Pipes",
    "Win32_System_Threading",
    "Win32_UI_WindowsAndMessaging",
] }

[dev-dependencies]
tempfile = "3"
